[package]
name = "config"
version = "0.11.0"
description = "Layered configuration system for Rust applications."
homepage = "https://github.com/mehcode/config-rs"
repository = "https://github.com/mehcode/config-rs"
readme = "README.md"
keywords = ["config", "configuration", "settings", "env", "environment"]
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
categories = ["config"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["toml", "json", "yaml", "ini", "ron", "json5"]
json = ["serde_json"]
yaml = ["yaml-rust"]
ini = ["rust-ini"]
json5 = ["json5_rs"]
preserve_order = ["indexmap", "toml/preserve_order", "serde_json/preserve_order", "ron/indexmap"]

[dependencies]
async-trait = "0.1.52"
lazy_static = "1.4.0"
serde = "1.0.132"
nom = "7.1.0"

toml = { version = "0.5.8", optional = true }
serde_json = { version = "1.0.73", optional = true }
yaml-rust = { version = "0.4.5", optional = true }
rust-ini = { version = "0.17.0", optional = true }
ron = { version = "0.7.0", optional = true }
json5_rs = { version = "0.4.1", optional = true, package = "json5" }
indexmap = { version = "1.7.0", features = ["serde-1"], optional = true }
pathdiff = "0.2.1"

[dev-dependencies]
serde_derive = "1.0.132"
float-cmp = "0.9.0"
chrono = { version = "0.4.19", features = ["serde"] }
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "fs", "io-util", "time"] }
warp = "0.3.2"
futures = "0.3.19"
reqwest = "0.11.8"
